development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV["DISABLE_REDIS"].present? ? "async" : "redis" %>
  url: <%= ENV["DISABLE_REDIS"].present? ? nil : ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: homey_challenge_production
  ssl_params:
    verify_mode: OpenSSL::SSL::VERIFY_NONE
